const data = {
  users: [
    {
      name: "Hashir Khan",
      email: "khnhashir555@gmail.com",
      password: "hashirkhangarmentscityadmin",
      isAdmin: true,
      image:
        "https://lh3.googleusercontent.com/a-/AOh14GiViKeeKJyE-Sicc0eGXRpLJ74s3jjcOgO9sPxu=s96-c",
      gender: "Male",
    },
  ],

  products: [
    {
      description: "Long Sleeves T-Shirt",
      image: "/images/image1.png",
      price: 1600,
      reviews: 0,
      brand: "Nike",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "shirt",
      collec: "summer",
      gender: "male",
      gender: "female",
    },
    {
      description: "Champion Hoodie",
      image: "/images/image2.png",
      price: 2300,
      reviews: 0,
      brand: "Champion",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "hoodie",
      collec: "winter",
      gender: "male",
    },
    {
      description: "Kurta Pajama",
      image: "/images/image3.png",
      price: 1000,
      reviews: 0,
      brand: "Nike",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "kurta",
      collec: "summer",
      gender: "female",
    },
    {
      description: "Flannel Shirt Jacket",
      image: "/images/image4.png",
      price: 800,
      reviews: 0,
      brand: "Zara",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "jacket",
      collec: "winter",
      gender: "male",
    },
    {
      description: "Polar Fleece Jacket",
      image: "/images/image5.png",
      price: 850,
      reviews: 0,
      brand: "Zara",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "jacket",
      collec: "winter",
      gender: "female",
    },
    {
      description: "Champion T-Shirt",
      image: "/images/image6.png",
      price: 550,
      reviews: 0,
      brand: "Champion",
      sizes: [
        { size: "small", stock: 20 },
        { size: "medium", stock: 10 },
        { size: "large", stock: 0 },
      ],
      ratings: 0,
      category: "shirt",
      collec: "summer",
      gender: "male",
    },
    {
      description: "Full Zip Hooded Fleece Sweatshirt",
      image: "/images/image7.png",
      price: 2700,
      reviews: 0,
      brand: "Zara",
      sizes: [{ size: "wallete", stock: 20 }],
      ratings: 0,
      category: "hoodie",
      collec: "winter",
      gender: "female",
    },
    {
      description: "Performance Training Pant with Pockets",
      image: "/images/image8.png",
      price: 600,
      reviews: 0,
      brand: "Nike",
      sizes: [
        { size: "3", stock: 20 },
        { size: "5", stock: 10 },
        { size: "7", stock: 0 },
      ],
      ratings: 0,
      category: "pants",
      collec: "summer",
      gender: "male",
    },
  ],
};

module.exports = data;
